name: Github Actions Hello World
on: [push]
jobs:
  Hello-World-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "イベントトリガー / ${{ github.event_name }}"
      - run: echo "実行環境 / ${{ runner.os }}"
      - run: echo "ブランチ / ${{ github.ref }} @ ${{ github.repository }}"


      - name: ファイルのチェックアウト
        uses: actions/checkout@v4


      - name: リポジトリ内のファイル
        run: |
          ls ${{ github.workspace }}
